### PR TITLE
Force ticks to be serialized with the extension 't'

### PR DESCRIPTION
**Pull request by Norazan**
Make sure configs of other plugins that use TimeSpan are updated accordingly!

Closes #13

### CODE REVIEW

**Review by 0ffz — APPROVED** [review]
Since we're at it, do you think it's worth renaming the conversions to inTicks, inSeconds, etc?

**Comment by Norazan** [comment]
You're talking about the Number to TimeSpan conversions or the TimeSpan to Double?

**Comment by 0ffz** [comment]
Timespan to double. That way youd be able to say 10.ticks.inSeconds, right now it looks like 10.ticks.seconds which I think doesn't make much sense.

**Comment by Norazan** [comment]
Sure why not, I'll add a commit.

**Review by 0ffz — APPROVED** [review]

**Pull request merged**
