### PR TITLE
change paper repo-url

### PR DESCRIPTION
**Pull request by Boy0000**

### CODE REVIEW

**Review by 0ffz — APPROVED** [review]

**Review by 0ffz — APPROVED** [review]
Actually hold on, just replace all instances of `https://repo.codemc.io/repository/maven-snapshots` in the repo, it's present in other places

**Review by 0ffz — CHANGES_REQUESTED** [review]
Dammit meant to deny lol

**Comment by Boy0000** [comment]
Its not present in any project because it all gets paper from Deps.papermc or whatever.
Which fails to get fetched because they changed their repository link

**Comment by Boy0000** [comment]
whatever it was, it seems to be fixed

**Pull request closed without merging**
