### PR TITLE
Add particle & icon

### PR DESCRIPTION
**Pull request by Boy0000**

### CODE REVIEW

**Comment by 0ffz** [comment]
Since we're at it, I think I didn't do this earlier because of default values but using this method this shouldn't be a problem and the serializer would be a lot cleaner. https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#composite-serializer-via-surrogate

**Comment by Boy0000** [comment]
@0ffz something like that?
Would we wanna do this in any other serializers aswell?

**Comment by 0ffz** [comment]
Yep looks right. Id like to change all of them at some point but feel free to just do this one for now if you like

**Review by 0ffz — APPROVED** [review]

**Comment by Boy0000** [comment]
I'll merge this as i need icon etc. Opened #35 and ill try and get a few more in shortly there

**Pull request merged**
